### ISSUE TITLE
IDO Contract Requirement

### ISSUE THREAD

**Issue by synassets** [synassets/contracts#3]
1. Every whitelist has fixed 1000 USDC similarly.
 2. Every address can have many whitelists,and transfer the whitelists to others.
 3. If someone has one whitelist and he had participant the IDO,then he can't transfer WL to others.
 4. Invite reward will include two part ,one part is the 2.5% reward that send to ambassadors when the IDO,another part is the 1.5% reward that send to a address and will send to ambassadors after the IDO.

**Comment by UdoEtimbuk** [comment]
Great!
